[package]
name = "iced_audio"
version = "0.8.0"
authors = ["Billy Messenger <https://github.com/BillyDM>"]
license = "MIT"
edition = "2021"
keywords = ["iced", "gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "An extension to the Iced GUI library with useful widgets for audio applications"
homepage = "https://github.com/iced-rs/iced_audio"
documentation = "https://docs.rs/iced_audio"
repository = "https://github.com/iced-rs/iced_audio"
readme = "README.md"
resolver = "2"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = [
    "examples/simple",
    "examples/inputs_tour",
]

[features]
default = ["wgpu"]
glow = ["iced_glow"]
wgpu = ["iced_wgpu"]

[dependencies]
iced_core = "0.6"
iced_glow = { version = "0.4", optional = true }
iced_graphics = { version = "0.4", features = ["canvas"] }
iced_native = "0.6"
iced_wgpu = { version = "0.6", optional = true }

[dev-dependencies]
iced = "0.5"
