name: CI

on: [push, pull_request]

jobs:
  hygiene:
    name: Hygiene
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: fmt
      run: cargo fmt -- --check
    - name: clippy
      run: cargo clippy --all-targets

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
